config/urls.py
from django.contrib import admin
from django.urls import path,include
from config.settings.development import DEBUG,STATIC_URL,STATIC_ROOT,MEDIA_ROOT,MEDIA_URL
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
  
]
if DEBUG:
    urlpatterns  =  urlpatterns + static(STATIC_URL, document_root=STATIC_ROOT)
    urlpatterns  =  urlpatterns + static(MEDIA_URL, document_root=MEDIA_ROOT)

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from .views import (index,ItemView,customer_details,register_customer
,vehicle_form,
save_vehicle,
payment_form,
payment_save_details,contact_us,save_contact_us)

app_name = 'mainapp'


urlpatterns = [
    path('',index, name = "index_page"),
    path('parking/<slug>/', ItemView.as_view(), name='parkingdetail'),
    path('payment/customer_details/', customer_details, name='customerdetails'),
    path('payment/register_customer/',register_customer, name= "register_customer"),
    path('payment/register_vehicle/',vehicle_form, name= "vehicle_register"),
    path('payment/save_vehicle/',save_vehicle, name= "vehicle_save"),
    path('payment/form/',payment_form, name= "payment_form"),
    path('payment/form/save/',payment_save_details, name= "payment_save_details"),
    path('contact_us/',contact_us, name= "contact_us"),
    path('contact_us/save/',save_contact_us, name= "save_contact_us"),


    
   
]

mainapp/models.py
from django.db import models
from django.db.models.query import ModelIterable
from django.db import models
import random
import os
from django.db.models import Q
from datetime import datetime
from django.utils.timezone import now
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from mainapp.utils import unique_slug_generator,category_unique_slug_generator
import uuid

# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "parking/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )


class Parking(models.Model):
    CHOICES = (
        ('PR', 'Parking Facility'),
        ('OS', 'Open Space'),
        
    )
  


    parking_area_name  = models.CharField(max_length=100)
    parking_cost_per_hour = models.IntegerField()
    parking_location = models.CharField(max_length=150)
    parking_facility = models.CharField(max_length=300, choices = CHOICES)
    security_inclusive  = models.BooleanField(default=False)
    carwash_available = models.BooleanField(default=False)
    nearby_restaurant = models.BooleanField(default=False)
    parking_picture = models.FileField(upload_to = upload_image_path ,null=True,blank=False)
    parking_overview = models.TextField(blank=True,null= True)
    
    slug = models.SlugField(blank=True,unique=True,default=uuid.uuid4)

    def __str__(self):
        return self.parking_area_name

    def get_absolute_url(self):
        return reverse("mainapp:parkingdetail", kwargs={
            'slug': self.slug
        })






class ParkingSlots(models.Model):
    CHOICES2 = (
        ('PR', 'Parking Facility'),
        ('OS', 'Open Space'),
        
    )
  

    parking_id = models.ForeignKey(Parking, on_delete=models.CASCADE)
    parking_picture = models.FileField(upload_to = upload_image_path ,null=True,blank=False)
    booked = models.BooleanField(default=False)
    

    def __str__(self):
        return self.parking_id.parking_area_name


class Customer(models.Model):
    parking_id = models.ForeignKey(ParkingSlots, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=150)
    customer_id_no = models.CharField(max_length=150)
    customer_email = models.EmailField()
    customer_phone_number = models.CharField(max_length=150)

    def __str__(self):
        return self.customer_name


class Vehicle(models.Model):
    customer_id = models.ForeignKey(Customer, on_delete=models.CASCADE)
    vehicle_model = models.CharField(max_length=150)
    manufacture_year = models.CharField(max_length=150)
    vehicle_number_plate = models.CharField(max_length=150)

    def __str__(self):
        return self.customer_id.customer_name
    


class Payment(models.Model):
     
    vehicle_id = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    card_payment = models.BooleanField(default=False)
    paypal_payment = models.BooleanField(default=False)
    terms_condition = models.BooleanField(default=False)
    hours = models.IntegerField()
    total_payment = models.DecimalField(max_digits=90,decimal_places=2,blank=True,null=True)

    def __str__(self):
        return self.vehicle_id.customer_id.customer_name



class ContactUs(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=150)
    email = models.EmailField()
    subject = models.CharField(max_length=150)
    your_company = models.CharField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return self.first_name
    
    


    
    

    

mainapp/forms.py
from .models import Customer,Vehicle,Payment,ContactUs
from django import forms



class CustomerForm(forms.ModelForm):
    class Meta:
        model =  Customer
        fields = ['customer_name','customer_id_no','customer_email','customer_phone_number']
        widgets = {
            'customer_name' : forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control"
                }
            ),
            'customer_phone_number' : forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control"
                }
            ),
             'customer_id_no' : forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control"
                }
            ),
            'customer_email' : forms.TextInput(
                attrs={
                    "type":"email", "class":"form-control"
                }
            ),

            

        }


class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ['vehicle_model','manufacture_year','vehicle_number_plate']
        widgets = {
            'vehicle_model' : forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control"
                }
            ),
            'manufacture_year' : forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control"
                }
            ),
             'vehicle_number_plate' : forms.TextInput(
                attrs={
                    "type":"text", "class":"form-control"
                }
            )
            

            

        }
    

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['hours','card_payment','paypal_payment','terms_condition']
        widgets = {
            'hours' : forms.TextInput(
                attrs={
                    "type":"number", "class":"form-control"
                }
            ),
            'card_payment' : forms.CheckboxInput(
                attrs={
                    "class":"form-check-input", "type":"checkbox"
                }
            ),
            "paypal_payment" : forms.CheckboxInput(
                attrs={
                   "class":"form-check-input", "type":"checkbox"
                }
            ),
             "terms_condition" : forms.CheckboxInput(
                attrs={
                    "class":"form-check-input", "type":"checkbox"
                }
            ),

        }


class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['first_name','last_name','phone_number','email','subject','your_company','message']
        widgets = {
            'first_name' : forms.TextInput(
                attrs={
                    " type":"text", "class":"form-control" ,"required":""
                }
            ),
            'last_name' : forms.TextInput(
                attrs={
                   " type":"text", "class":"form-control" ,"required":""  
                }
            ),
             'phone_number' : forms.TextInput(
                attrs={
                   " type":"text", "class":"form-control" ,"required":""  
                }
            ),

             'subject' : forms.TextInput(
                attrs={
                   " type":"text", "class":"form-control" ,"required":""  
                }
            ),

              'subject' : forms.TextInput(
                attrs={
                   " type":"text", "class":"form-control" ,"required":""  
                }
            ),

                'your_company' : forms.TextInput(
                attrs={
                   " type":"text", "class":"form-control" ,"required":""  
                }
            ),

            'message' : forms.Textarea(
                attrs={
                   "class":"form-control", "rows":"3","required":""  
                }
            ),

             'email' : forms.EmailInput(
                attrs={
                   " type":"email", "class":"form-control" ,"required":""  
                }
            ),
            
            

        }
        

mainapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
import datetime
from .models import Parking,ParkingSlots,Customer,Vehicle
from .forms import CustomerForm,VehicleForm,PaymentForm,ContactUsForm
from django.views.generic import DetailView,View,ListView

# Create your views here.

def index(request):
    parking = Parking.objects.all()
    context = {
        'parking' : parking
    }
    return render(request,'index.html',context)


class ItemView(DetailView):
    model = Parking
    template_name = "index_detailed.html"
    def get_context_data(self, **kwargs):
        parking_slots = ParkingSlots.objects.all()
        context = super().get_context_data(**kwargs)
        context["parking_slots"] = parking_slots
        return context

def customer_details(request):
    form = CustomerForm()
    parking_id = request.POST.get("product_id")
    request.session["parking_slot_id"] = parking_id
    context = {
        'form' : form
    }
    
    return render(request,'customer_booking.html',context)


def register_customer(request):
    form = CustomerForm(request.POST or None)
    if form.is_valid:
        instance = form.save(commit=False)
        parking_id_jj = request.session.get("parking_slot_id")
        parking_slot = ParkingSlots.objects.get(id = parking_id_jj )
        instance.parking_id = parking_slot
        instance.save()
        request.session["customer_id_registered"] = instance.id
        return redirect("mainapp:vehicle_register")
    return redirect("/")


def vehicle_form(request):
    form = VehicleForm()
    context = {
        "form":form
    }
    return render(request,'vehicle_details.html',context)

def save_vehicle(request):
    form = VehicleForm(request.POST or None)
    if form.is_valid:
        instance   =  form.save(commit=False)
        registered_customer = request.session.get("customer_id_registered")
        customer = Customer.objects.get(id = registered_customer)
        instance.customer_id = customer
        instance.save()
        request.session["vehicle_id"] = instance.id
        return redirect("mainapp:payment_form")
    return redirect("/")


def payment_form(request):
    form = PaymentForm()
    context = {
        'form': form
    }
    return render(request,'checkin_details.html',context)

def payment_save_details(request):
    form =  PaymentForm(request.POST or None)
    if form.is_valid:
        instance   =  form.save(commit=False)
        parking_id_jj = request.session.get("parking_slot_id")
        parking_slot = ParkingSlots.objects.get(id = parking_id_jj )
        vehicle_id = request.session.get("vehicle_id")
        vehicle = Vehicle.objects.get(id = vehicle_id)
        instance.vehicle_id = vehicle
        instance.total_payment = float(parking_slot.parking_id.parking_cost_per_hour) * float(instance.hours)
        instance.save()
        parking_slot.booked = True
        parking_slot.save()
        del request.session["parking_slot_id"]
        del request.session["vehicle_id"]
        del request.session["customer_id_registered"]
        return redirect("/")

    return redirect("/")


def contact_us(request):
    form = ContactUsForm()
    context = {
        "form" : form
    }
    return render(request,'contact_us.html',context)

def save_contact_us(request):
    #checking contact if submited
    form =  ContactUsForm(request.POST or None)
    print("contact submited ", form.data)
    if form.is_valid:
        form.save()
        print(".....form saved......")
        return redirect("/")
    return redirect("/")

mainapp/templates/checkin_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ================ Inner banner ================ -->
<div class="inner-banner inner-banner-bg pt-70 pb-40">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8 col-md-8 mb-30"> 
        <!-- page-title -->
        <div class="page-title">
          <h1>Customer Information</h1>
        </div>
        <!-- page-title end --> 
      </div>
      <div class="col-lg-4 col-md-4 mb-30"> 
        <!-- breadcrumb -->
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
        
        </ol>
        <!-- breadcrumb end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Inner banner end ================ --> 

<!-- ================ Payment Information page ================ -->
<div class="detail-page pt-70 pb-40">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mb-30">
        <form class="form-style-1" method="POST"  action="{% url 'mainapp:payment_save_details' %}"  >
        {% csrf_token %}
          <h4 class="mb-15">Card Details</h4>
          <div class="card-type">
            <div class="row">
              <div class="col-lg-6 mb-20">
                <div class="card-type-img border rounded p-20 text-center position-relative">
                  {{form.card_payment}}
                  <img src="{% static  'img/card-type-img-1.jpg' %}" alt=""> </div>
              </div>
              <div class="col-lg-6 mb-20">
                <div class="card-type-img border rounded p-20 text-center position-relative">
                  {{form.paypal_payment}}
                  <img src="{% static 'img/card-type-img-2.jpg' %}" alt=""> </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Parking Hours<span class="text-danger">*</span></label>
                {{form.hours}}
              </div>
            </div>
          
          </div>
          
          <div class="form-group form-check">
            {{form.terms_condition}}
            <label class="form-check-label font-size-14" for="exampleCheck1">By continuing, you agree to the <a href="">Terms and Conditions.</a></label>
          </div>
          <button type="submit" class="btn-style-1">Book</button>
        </form>
      </div>
      <div class="col-lg-4 col-md-4">
        <aside> 
          <!-- filter widget -->
         
          <!-- filter widget end --> 
          <!-- help us -->
          <div class="help-us mb-30">
            <h3>How can we help you?</h3>
            <p>Lorem ipsum dolor sit ametdf consectetur adipiscing elitdgsh ametdf consectetur piscing.</p>
            <a class="view-detail-btn" href="{% url "mainapp:contact_us" %}"><i class="fas fa-phone-alt"></i> Contact Us</a> </div>
          <!-- help us end --> 
        </aside>
      </div>
    </div>
  </div>
</div>
<!-- ================ Payment Information page end ================ --> 

{% endblock content %}

mainapp/templates/contact_us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- ================ Inner banner ================ -->
<div class="inner-banner inner-banner-bg pt-70 pb-40">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8 col-md-8 mb-30"> 
        <!-- page-title -->
        <div class="page-title">
          <h1>Contact Us</h1>
        </div>
        <!-- page-title end --> 
      </div>
      <div class="col-lg-4 col-md-4 mb-30"> 
        <!-- breadcrumb -->
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active">Contact Us</li>
        </ol>
        <!-- breadcrumb end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Inner banner end ================ --> 


<!-- ================ Contact Us page ================ -->
<div class="contact-us-page pt-70 pb-40">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mb-30"> 
        <!-- contact form -->
        <form class="form-style-1" method="post" enctype="multipart/form-data" action="{% url 'mainapp:save_contact_us' %}"  >
        {% csrf_token %}
          <h4 class="mb-6">Contact Form</h4>
          <p>Fill out the form below, we will get back you soon.</p>
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>First Name<span class="text-danger">*</span></label>
                {{form.first_name}}
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <label>Last Name<span class="text-danger">*</span></label>
                {{form.last_name}}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Phone Number<span class="text-danger">*</span></label>
                {{form.phone_number}}
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <label>Email<span class="text-danger">*</span></label>
               {{form.email}}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Subject</label>
                {{form.subject}}
                              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <label>Your Company</label>
                {{form.your_company}}
              </div>
            </div>
          </div>
          <div class="form-group">
            <label>Write Your Message<span class="text-danger">*</span></label>
            {{form.message}}
          </div>
          <button type="submit" class="btn-style-1">Submit Now</button>
        </form>
        <!-- contact form end --> 
      </div>
      <div class="col-lg-4 col-md-4"> 
        <!-- contact info -->
        <div class="contact-info"> 
          <!-- contact info box -->
          <div class="contact-info-box mb-30">
            <h5 class="mb-8">Visit our location</h5>
            <p class="mb-0">Lorem ipsum dolor sit amet consectetur adipiscing elit amet consectetur.</p>
          </div>
          <!-- contact info box end --> 
          <!-- contact info box -->
          <div class="contact-info-box mb-30">
            <h5 class="mb-8">Message us</h5>
            <p class="mb-6"><a href="">info@exampal.com</a></p>
            <p class="mb-6"><a href="">+01 123 456 789</a></p>
          </div>
          <!-- contact info box end --> 
          <!-- contact info box -->
          <div class="contact-info-box mb-30">
            <h5 class="mb-8">Follow Us</h5>
            <ul class="list-inline">
              <li class="list-inline-item"><a href=""><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a href=""><i class="fab fa-twitter"></i></a></li>
              <li class="list-inline-item"><a href=""><i class="fab fa-linkedin-in"></i></a></li>
              <li class="list-inline-item"><a href=""><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item"><a href=""><i class="fab fa-pinterest-p"></i></a></li>
              <li class="list-inline-item"><a href=""><i class="fab fa-youtube"></i></a></li>
            </ul>
          </div>
          <!-- contact info box end --> 
          <!-- map -->
         
          <!-- map end --> 
        </div>
        <!-- contact info end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Contact Us page end ================ --> 


{% endblock content %}

mainapp/templates/customer_booking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ================ Inner banner ================ -->
<div class="inner-banner inner-banner-bg pt-70 pb-40">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8 col-md-8 mb-30"> 
        <!-- page-title -->
        <div class="page-title">
          <h1>Customer Information</h1>
        </div>
        <!-- page-title end --> 
      </div>
      <div class="col-lg-4 col-md-4 mb-30"> 
        <!-- breadcrumb -->
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
        
        </ol>
        <!-- breadcrumb end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Inner banner end ================ --> 

<!-- ================ Payment Information page ================ -->
<div class="detail-page pt-70 pb-40">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mb-30">
        <form class="form-style-1" method="POST"  action="{% url 'mainapp:register_customer' %}"  >
        {% csrf_token %}
          <h4 class="mb-15">Customer Details</h4>
          
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Customer Name<span class="text-danger">*</span></label>
                {{form.customer_name}}
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <label>Customer Phone<span class="text-danger">*</span></label>
                {{form.customer_phone_number}}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-4">
              <div class="form-group">
                <label>Customer Id No<span class="text-danger">*</span></label>
                {{form.customer_id_no}}
              </div>
            </div>
            <div class="col-lg-4">
              <div class="form-group">
                <label>Customer Email<span class="text-danger">*</span></label>
                {{form.customer_email}}
              </div>
            </div>
           
          </div>
         
          <button type="submit" class="btn-style-1">Continue</button>
        </form>
      </div>
      <div class="col-lg-4 col-md-4">
        <aside> 
          <!-- filter widget -->
         
          <!-- filter widget end --> 
          <!-- help us -->
          
          <!-- help us end --> 
        </aside>
      </div>
    </div>
  </div>
</div>
<!-- ================ Payment Information page end ================ --> 

{% endblock content %}

mainapp/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ================ Inner banner ================ -->
<div class="inner-banner inner-banner-bg pt-70 pb-40">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8 col-md-8 mb-30"> 
        <!-- page-title -->
        <div class="page-title">
          <h1>RIZAVU</h1>
        </div>
        <!-- page-title end --> 
      </div>
      <div class="col-lg-4 col-md-4 mb-30"> 
        <!-- breadcrumb -->
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
         
        </ol>
        <!-- breadcrumb end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Inner banner end ================ --> 


<!-- ================ Listing page ================ -->
<div class="listing-page pt-70 pb-40">
  <div class="container">
    <div class="row">
      <div class="col-lg-3">
        <aside> 
          <!-- sidebar -->
          <div class="desktop-filter-sidebar"> 
        
            <!-- filter widget end --> 
            <!-- filter widget -->
        
            <!-- filter widget end --> 
            <!-- filter widget -->
       
            <!-- filter widget end --> 
            <!-- filter widget -->
           
            <!-- filter widget end --> 
            <!-- help us -->
            <div class="help-us mb-30">
              <h3>How can we help you?</h3>
            
              <a class="view-detail-btn" href="{% url "mainapp:contact_us" %}"><i class="fas fa-phone-alt"></i> Contact Us</a> </div>
            <!-- help us end --> 
          </div>
          <!-- sidebar end --> 
        </aside>
      </div>
      <div class="col-lg-9"> 
        <!-- hotel results list -->
        <div class="hotel-results-list"> 
        {% if parking %}
        
        {% for p in parking %}
       
          <!-- list box -->
          <div class="list-box mb-30">
            <div class="owl-carousel list-box-carousel">
              <figure class="item"> <img src="{{p.parking_picture.url}}" alt="img description"> </figure>
          
            </div>
            <div class="list-box-content">
              <div class="list-box-title">
                <h3>{{p.parking_area_name}}<span>Ksh{{p.parking_cost_per_hour}}<em>/ hour</em></span></h3>
                <address>
                <i class="fas fa-map-marker-alt"></i> {{p.parking_location}}
                </address>
              </div>
              <div class="list-box-rating"> <span class="at-stars"> </i></span></div>
              <ul class="hotel-featured">
                
                {% if p.parking_facility == 'PR' %}
                <li><span><i class="fas fa-car"></i>Parking Facility</span></li>
                {% else %}
                <li><span><i class="fas fa-car"></i>Open Space</span></li>
                {% endif %}
                {% if p.security_inclusive %}
                <li><span><i class="fas fa-shield-alt"></i> Security inclusive</span></li>
                {% endif %}
                {% if p.carwash_available %}
                <li><span><i class="fas fa-car"></i> Carwash availabe</span></li>
                {% endif %}
                {% if p.nearby_restaurant %}
                <li><span><i class="fas fa-coffee"></i>Near restaurant Available</span></li>
                {% endif %}
              </ul>
              <div class="btn-wrapper mt-20 d-inline-block w-100"> <a class="view-detail-btn" href="{{p.get_absolute_url}}">View Details</a>  </div>
            </div>
          </div>
          <!-- list box end --> 
       
          {% endfor %}
        {% endif %}
         
        </div>
        <!-- hotel results list end --> 
        <!-- pagination -->
      
        <!-- pagination end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Listing page end ================ --> 



{% endblock content %}

mainapp/templates/vehicle_details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!-- ================ Inner banner ================ -->
<div class="inner-banner inner-banner-bg pt-70 pb-40">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-8 col-md-8 mb-30"> 
        <!-- page-title -->
        <div class="page-title">
          <h1>Customer Information</h1>
        </div>
        <!-- page-title end --> 
      </div>
      <div class="col-lg-4 col-md-4 mb-30"> 
        <!-- breadcrumb -->
        <ol class="breadcrumb mb-0">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
        
        </ol>
        <!-- breadcrumb end --> 
      </div>
    </div>
  </div>
</div>
<!-- ================ Inner banner end ================ --> 

<!-- ================ Payment Information page ================ -->
<div class="detail-page pt-70 pb-40">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 mb-30">
        <form class="form-style-1"  method="POST"  action="{% url 'mainapp:vehicle_save' %}"  >
        {% csrf_token %}
          <h4 class="mb-15">Vehicle Details</h4>
          <div class="card-type">
            <div class="row">
              
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="form-group">
                <label>Vehicle Model<span class="text-danger">*</span></label>
                {{form.vehicle_model}}
              </div>
            </div>
            <div class="col-lg-6">
              <div class="form-group">
                <label>Year of manufacture <span class="text-danger">*</span></label>
                {{form.manufacture_year}}
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-4">
              <div class="form-group">
                <label>Vehicle number plate<span class="text-danger">*</span></label>
                {{form.vehicle_number_plate}}
              </div>
            </div>
           
           
          </div>
          
          <button type="submit" class="btn-style-1">Continue</button>
        </form>
      </div>
      <div class="col-lg-4 col-md-4">
        <aside> 
          <!-- filter widget -->
         
          <!-- filter widget end --> 
          <!-- help us -->
          <div class="help-us mb-30">
            <h3>How can we help you?</h3>
            <p>Lorem ipsum dolor sit ametdf consectetur adipiscing elitdgsh ametdf consectetur piscing.</p>
            <a class="view-detail-btn" href="{% url "mainapp:contact_us" %}"><i class="fas fa-phone-alt"></i> Contact Us</a> </div>
          <!-- help us end --> 
        </aside>
      </div>
    </div>
  </div>
</div>
<!-- ================ Payment Information page end ================ --> 

{% endblock content %}